// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZ0oM1u7HBLFFOCB6dPTvL4aPLNAJLi8',
    appId: '1:110471224412:web:d6acabce7bf6683dd95a99',
    messagingSenderId: '110471224412',
    projectId: 'chatme-2cd2b',
    authDomain: 'chatme-2cd2b.firebaseapp.com',
    storageBucket: 'chatme-2cd2b.appspot.com',
    measurementId: 'G-ZP0BBVRJH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfDS2klH7XKmD_KiPrJe-4r6mSDheu6VE',
    appId: '1:110471224412:android:4a20fa2383e24c40d95a99',
    messagingSenderId: '110471224412',
    projectId: 'chatme-2cd2b',
    storageBucket: 'chatme-2cd2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmy39o_GXLOIkf-Kox5ULeRZOAaDXTxrU',
    appId: '1:110471224412:ios:0b6f7a0a7dfa0442d95a99',
    messagingSenderId: '110471224412',
    projectId: 'chatme-2cd2b',
    storageBucket: 'chatme-2cd2b.appspot.com',
    iosBundleId: 'com.example.chatme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmy39o_GXLOIkf-Kox5ULeRZOAaDXTxrU',
    appId: '1:110471224412:ios:0b6f7a0a7dfa0442d95a99',
    messagingSenderId: '110471224412',
    projectId: 'chatme-2cd2b',
    storageBucket: 'chatme-2cd2b.appspot.com',
    iosBundleId: 'com.example.chatme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZ0oM1u7HBLFFOCB6dPTvL4aPLNAJLi8',
    appId: '1:110471224412:web:e00772aa11c6c462d95a99',
    messagingSenderId: '110471224412',
    projectId: 'chatme-2cd2b',
    authDomain: 'chatme-2cd2b.firebaseapp.com',
    storageBucket: 'chatme-2cd2b.appspot.com',
    measurementId: 'G-RRNR87RQV9',
  );
}
